name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
     env:
      DATABASE_URL: "sqlite:///./test.db"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          python -m pip install ruff black

      - name: Ruff (lint)
        run: ruff check .

      - name: Black (format check)
        run: black --check .

      - name: Pytest
        run: pytest --cov=app --cov-report=term-missing --cov-fail-under=80 -q
