name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python - pip install -r requirements.txt
      - run: ruff check .
      - run: black --check .
      - run: pytest --cov=app --cov-report=term-missing -q
      # (Optional) cache pip downloads to speed up runs
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # If you have requirements.txt, prefer: pip install -r requirements.txt
          python -m pip install "uvicorn[standard]" fastapi pydantic httpx sqlmodel \
                                 pytest pytest-cov ruff black

      # ---- Lint & format ----
      - name: Ruff (lint)
        run: ruff check .
      - name: Black (format check)
        run: black --check .

      # ---- Tests + coverage ----
      - name: Pytest (with coverage)
        run: pytest --cov=app --cov-report=term-missing -q